In [56]:
import numpy as np
import pandas as pd


In [57]:
train = pd.read_csv('dataset/train.csv')
train = train.sample(frac=1)
print(train.shape)
train.head()

(23145, 28)


sofifa_id  age  height_cm  weight_kg    nationality              club  \
21388     228928   21        183         76       Scotland         Morecambe   
15524     228917   23        173         75  United States        AC Ajaccio   
18827     222174   30        178         73       China PR  Beijing Renhe FC   
6869      205857   29        190         76   South Africa     Kaizer Chiefs   
2733      191625   27        187         81         Brazil     Estoril Praia   

       overall  potential    value preferred_foot  ...  passing  dribbling  \
21388       55         64   120000          Right  ...       29         31   
15524       63         72   575000          Right  ...       49         65   
18827       59         59   140000          Right  ...       53         61   
6869        69         70  1000000          Right  ...       45         51   
2733        74         75  6500000          Right  ...       64         73   

       defending  physic gk_diving gk_handling  gk_kicking  gk_reflexes  \
21388         56      63        13          13          13           13   
15524         23      61        13          13          13           13   
18827         62      63        13          13          13           13   
6869          68      72        13          13          13           13   
2733          33      76        13          13          13           13   

       gk_speed  gk_positioning  
21388        13              13  
15524        13              13  
18827        13              13  
6869         13              13  
2733         13              13  

[5 rows x 28 columns]

In [58]:
train['team_position'] = train['team_position'].fillna("RES")
train['release_clause_eur'] = train['release_clause_eur'].fillna(0)
train.to_csv("train.csv", index=False)

In [59]:
train.shape

(23145, 28)

In [60]:
not_req = ['value', 'sofifa_id']
cols = [x for x in train.columns.tolist() if x not in not_req]

In [61]:
X_train_pd = train[cols]
X_labels_pd = train['sofifa_id']

In [62]:
X_train_pd = pd.get_dummies(X_train_pd, columns=['team_position', 'nationality', 'club', 'team_position', 'nation_position', 'preferred_foot'])
y_train_pd = pd.get_dummies(train['value'])

In [63]:
X_train = np.array(X_train_pd).astype(np.int32)
X_train[0]

array([ 21, 183,  76, ...,   0,   0,   1], dtype=int32)

In [64]:
y_train = np.array(y_train_pd).astype(np.int32)
y_train[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [65]:
X_labels = np.array([X_labels_pd]).astype(np.int32).T
X_labels[0]

array([228928], dtype=int32)

In [66]:
import pickle

pickle.dump(X_train, open("X_train.pkl", "wb"))
pickle.dump(y_train, open("y_train.pkl", "wb"))